[workspace]
members = [
            "assets_demo",
            "physics_demo",
            "scene_tree_test",
            "spawn_scene",
            "dodge_the_creeps",
            "node_tree_view",
        ]
resolver = "2"
