[package]
name = "scene_tree_test"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
path = "../run_godot.rs"
name = "scene_tree_test"

[lib]
crate-type = ["cdylib"]

[dependencies]
bevy = {version = "0.8", default-features = false}
bevy_godot = {path = "../.."}